include (${CMAKE_CURRENT_LIST_DIR}/Analyzer/CMakePackage.cmake)
include (${CMAKE_CURRENT_LIST_DIR}/Boundary/CMakePackage.cmake)
include (${CMAKE_CURRENT_LIST_DIR}/GKSSolver/CMakePackage.cmake)
include (${CMAKE_CURRENT_LIST_DIR}/Reader/CMakePackage.cmake)
include (${CMAKE_CURRENT_LIST_DIR}/Util/CMakePackage.cmake)
include (${CMAKE_CURRENT_LIST_DIR}/Writer/CMakePackage.cmake)
